### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Ashley-Westcott** [learn-co-curriculum/fewpjs-communicating-with-the-server#5]
Materials say "The data that comes back from the server is not sent in HTML. While (once) sent back in XML, it's not most often sent back in a format known as JSON ("Jay-Sawn"). JavaScript Object Notation (JSON) is a String that JavaScript knows how to turn into an Object. So, in this module, we'll also need to talk about JavaScript Objects."

Did you mean "it's NOW most often sent back..." instead of "it's NOT most often..."

**Comment by sgharms** [comment]
Correct! Willfix.
